name: StreamerSays
api-version: 1.16
authors: [DQMME]
main: de.dqmme.streamersays.StreamerSays
version: 1.0
commands:
  challenge:
    permission: streamersays.challenge
  gamemaster:
    permission: streamersays.gamemaster
  kit:
    permission: streamersays.kit
  item:
    permission: streamersays.item
  revive:
    permission: streamersays.revive
  clear:
    permission: streamersays.clear